FROM python:3.10-slim

WORKDIR /app

# 必要なPythonライブラリをインストール
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# アプリをコピー
COPY . /app

EXPOSE 8501

CMD ["streamlit", "run", "savan.py", "--server.port=8501", "--server.address=0.0.0.0"]
