# ワークフロー全体の名前
name: SAVAN Deploy to Google Cloud Run

# ワークフローを実行するきっかけ（トリガー）
on:
  push:
    branches:
      - main  # mainブランチにpushされた時だけ実行

# 環境変数の設定
env:
  PROJECT_ID: openif-469110 # あなたのGCPプロジェクトID
  GAR_LOCATION: asia-northeast1 # Artifact Registryの場所（東京）
  SERVICE_NAME: gantt-line # Cloud Runのサービス名

# 実行する仕事（ジョブ）の内容
jobs:
  deploy:
    # ジョブを実行する仮想環境の種類
    runs-on: ubuntu-latest

    # ジョブのステップ（実際の作業内容）
    steps:
      # ステップ1: リポジトリのコードを仮想環境にチェックアウトする
      - name: Checkout code
        uses: actions/checkout@v4

      # ステップ2: Google Cloudへ認証する
      # GCP_SA_KEYという金庫からキーカードを取り出して認証します
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # ステップ3: Google Cloud SDK (gcloudコマンド) をセットアップする
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      # ステップ4: アプリをコンテナという箱に詰めて、Googleの倉庫(Artifact Registry)に送る
      # --tagの後ろで、倉庫の場所とアプリの名前+バージョンを指定します
      - name: Build and Push Container
        run: |-
          gcloud builds submit --tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # ステップ5: Google Cloud Runに、倉庫の新しい箱を使ってアプリを公開するように命令する
      # --imageの後ろで、ステップ4で倉庫に送った箱を指定します
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.GAR_LOCATION }} \
            --platform managed \
            --allow-unauthenticated
