# ワークフロー全体の名前
name: SAVAN Deploy to Google Cloud Run

# ワークフローを実行するきっかけ（トリガー）
on:
  push:
    branches:
      - main  # mainブランチにpushされた時だけ実行

# 環境変数の設定
env:
  PROJECT_ID: openif-469110
  GAR_LOCATION: asia-northeast1
  SERVICE_NAME: gantt-line
  REPO_NAME: gantt-line

# 実行する仕事（ジョブ）
jobs:
  deploy:
    # このジョブはコミットメッセージに [to-gcp] が含まれる場合のみ実行する
    if: "contains(github.event.head_commit.message, '[to-gcp]')"
    # ジョブを実行する仮想環境の種類
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    # ジョブのステップ（実際の作業内容）
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_DEPLOY_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Build and Push Container
        run: |-
          gcloud builds submit . \
            --tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --project=${{ env.PROJECT_ID }} \
            --service-account="projects/${{ env.PROJECT_ID }}/serviceAccounts/${{ env.PROJECT_ID }}@cloudbuild.gserviceaccount.com"

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.GAR_LOCATION }} \
            --platform managed \
            --no-allow-unauthenticated \
            --set-env-vars="GCP_SA_KEY=${{ secrets.GCP_DEPLOY_KEY }}"